# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-02 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('position', models.CharField(max_length=32)),
                ('company', models.CharField(choices=[(1, '北京总公司'), (2, '上海分公司'), (3, '广州分公司')], max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
