# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200306_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatar/default.jpeg', upload_to='img/avatar'),
        ),
    ]
