# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-15 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='无', max_length=32),
            preserve_default=False,
        ),
    ]
