# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200304_0601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=models.CharField(default=1, max_length=256, verbose_name='文章摘要'),
            preserve_default=False,
        ),
    ]
